// <auto-generated />
using System;
using Freelancer.Backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Freelancer.Backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    [Migration("20250825160152_SeedForRatings")]
    partial class SeedForRatings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Freelancer.Backend.Domain.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Job", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 7, 26, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4082),
                            Description = "Projekt aplikacji mobilnej dla sklepu internetowego z wykorzystaniem Flutter i React Native.",
                            Name = "Rozwój aplikacji mobilnej e-commerce",
                            Price = 15000,
                            StartDate = new DateTime(2025, 8, 5, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4088),
                            Status = 0,
                            Tags = "[\"Flutter\",\"React Native\",\"E-Commerce\"]",
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 8, 10, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4092),
                            Description = "Dodanie logowania Google i obsługi powiadomień push w aplikacji mobilnej.",
                            Name = "Integracja Firebase w aplikacji mobilnej",
                            Price = 4000,
                            StartDate = new DateTime(2025, 8, 15, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4093),
                            Status = 1,
                            Tags = "[\"Firebase\",\"Push Notifications\",\"Mobile\"]",
                            UserId = 11
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 6, 26, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4095),
                            Description = "Tworzenie skalowalnej platformy e-commerce opartej o mikroserwisy w .NET i Javie.",
                            Name = "Budowa platformy e-commerce w .NET",
                            Price = 25000,
                            StartDate = new DateTime(2025, 7, 11, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4095),
                            Status = 0,
                            Tags = "[\".NET\",\"Java\",\"Microservices\",\"E-Commerce\"]",
                            UserId = 11
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 7, 31, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4097),
                            Description = "Projekt aplikacji webowej wspierającej proces rekrutacyjny i onboarding programistów.",
                            Name = "System do zarządzania rekrutacją IT",
                            Price = 7000,
                            StartDate = new DateTime(2025, 8, 10, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4098),
                            Status = 1,
                            Tags = "[\"ASP.NET Core\",\"HRTech\",\"Recruitment\"]",
                            UserId = 12
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2025, 8, 15, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4100),
                            Description = "Budowa platformy webowej z materiałami szkoleniowymi i check-listą onboardingu.",
                            Name = "Portal onboardingowy dla nowych pracowników",
                            Price = 3000,
                            StartDate = new DateTime(2025, 8, 20, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4101),
                            Status = 0,
                            Tags = "[\"Blazor\",\"ASP.NET Core\",\"Onboarding\"]",
                            UserId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2025, 7, 16, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4104),
                            Description = "Aplikacja webowa analizująca SEO stron i generująca raporty dla klientów.",
                            Name = "System analizy SEO",
                            Price = 8000,
                            StartDate = new DateTime(2025, 7, 26, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4104),
                            Status = 1,
                            Tags = "[\"SEO\",\"WebApp\",\"Analytics\"]",
                            UserId = 13
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2025, 8, 20, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4106),
                            Description = "Implementacja modułu generowania raportów z kampanii marketingowych.",
                            Name = "Moduł raportowania danych",
                            Price = 2000,
                            StartDate = new DateTime(2025, 8, 27, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4107),
                            Status = 0,
                            Tags = "[\"Reporting\",\"SQL\",\"Dashboard\"]",
                            UserId = 13
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2025, 8, 5, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4109),
                            Description = "Tworzenie nowoczesnego UI/UX dla aplikacji bankowej w Figma.",
                            Name = "Projekt interfejsu systemu bankowego",
                            Price = 12000,
                            StartDate = new DateTime(2025, 8, 15, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4109),
                            Status = 0,
                            Tags = "[\"UI\",\"UX\",\"Figma\"]",
                            UserId = 14
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2025, 8, 7, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4111),
                            Description = "Projekt systemu do zarządzania klientami i negocjacjami handlowymi.",
                            Name = "System CRM dla firmy B2B",
                            Price = 6000,
                            StartDate = new DateTime(2025, 8, 13, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4112),
                            Status = 1,
                            Tags = "[\"CRM\",\"B2B\",\"ASP.NET Core\"]",
                            UserId = 15
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2025, 8, 18, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4114),
                            Description = "Budowa platformy e-learningowej do szkoleń sprzedażowych.",
                            Name = "Aplikacja szkoleniowa online",
                            Price = 5000,
                            StartDate = new DateTime(2025, 8, 26, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4115),
                            Status = 0,
                            Tags = "[\"E-Learning\",\"Blazor\",\"WebApp\"]",
                            UserId = 15
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2025, 7, 6, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4117),
                            Description = "Wsparcie w prowadzeniu projektu IT z wykorzystaniem Scruma i Jiry.",
                            Name = "Koordynacja projektu w Agile",
                            Price = 9000,
                            StartDate = new DateTime(2025, 7, 16, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4117),
                            Status = 1,
                            Tags = "[\"Agile\",\"Scrum\",\"Jira\"]",
                            UserId = 16
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2025, 8, 3, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4120),
                            Description = "Analiza luk bezpieczeństwa i wdrożenie rozwiązań DevSecOps.",
                            Name = "Audyt bezpieczeństwa aplikacji webowej",
                            Price = 11000,
                            StartDate = new DateTime(2025, 8, 10, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4121),
                            Status = 0,
                            Tags = "[\"Security\",\"DevSecOps\",\"PenTest\"]",
                            UserId = 17
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2025, 8, 13, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4123),
                            Description = "Implementacja Prometheus i Grafana do monitorowania infrastruktury.",
                            Name = "System monitoringu serwerów",
                            Price = 5000,
                            StartDate = new DateTime(2025, 8, 18, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4123),
                            Status = 1,
                            Tags = "[\"Monitoring\",\"Prometheus\",\"Grafana\"]",
                            UserId = 17
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2025, 7, 21, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4130),
                            Description = "Zbieranie wymagań i projektowanie modelu danych dla ERP.",
                            Name = "Analiza biznesowa systemu ERP",
                            Price = 14000,
                            StartDate = new DateTime(2025, 7, 31, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4131),
                            Status = 0,
                            Tags = "[\"ERP\",\"SQL\",\"Business Analysis\"]",
                            UserId = 18
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2025, 8, 17, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4133),
                            Description = "Stworzenie architektury hurtowni danych dla systemu BI.",
                            Name = "Projekt hurtowni danych",
                            Price = 10000,
                            StartDate = new DateTime(2025, 8, 23, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4133),
                            Status = 1,
                            Tags = "[\"ETL\",\"Data Warehouse\",\"BI\"]",
                            UserId = 18
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2025, 8, 22, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4144),
                            Description = "Projekt aplikacji webowej do obsługi zgłoszeń klientów.",
                            Name = "System zgłoszeń helpdesk",
                            Price = 1500,
                            StartDate = new DateTime(2025, 8, 24, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4145),
                            Status = 0,
                            Tags = "[\"Helpdesk\",\"ASP.NET Core\",\"Support\"]",
                            UserId = 19
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2025, 8, 23, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4147),
                            Description = "Stworzenie panelu admina do zarządzania zgłoszeniami i SLA.",
                            Name = "Panel administracyjny dla helpdesk",
                            Price = 1000,
                            StartDate = new DateTime(2025, 8, 28, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4147),
                            Status = 1,
                            Tags = "[\"Admin Panel\",\"Support\",\"WebApp\"]",
                            UserId = 19
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2025, 8, 11, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4150),
                            Description = "Budowa prostego CMS do zarządzania artykułami IT.",
                            Name = "System zarządzania treściami",
                            Price = 4500,
                            StartDate = new DateTime(2025, 8, 20, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4150),
                            Status = 0,
                            Tags = "[\"CMS\",\"ASP.NET Core\",\"Content Management\"]",
                            UserId = 20
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2025, 8, 19, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4172),
                            Description = "Projekt REST API do eksportu danych do Excela i PDF.",
                            Name = "Moduł API do generowania raportów",
                            Price = 2500,
                            StartDate = new DateTime(2025, 8, 27, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4173),
                            Status = 1,
                            Tags = "[\"API\",\"REST\",\"Reporting\"]",
                            UserId = 20
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2025, 8, 5, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4175),
                            Description = "Migracja starej aplikacji .NET Framework do .NET 8.",
                            Name = "Refaktoryzacja aplikacji legacy",
                            Price = 9000,
                            StartDate = new DateTime(2025, 8, 13, 16, 1, 49, 647, DateTimeKind.Utc).AddTicks(4176),
                            Status = 0,
                            Tags = "[\".NET\",\"Refactoring\",\"Migration\"]",
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.JobPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobPhoto", (string)null);
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.JobRequest", b =>
                {
                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("JobId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("JobRequests");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.JobsUser", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("JobsUser");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CreatingUserId")
                        .HasColumnType("int");

                    b.Property<byte>("Rate")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Great work!",
                            CreatingUserId = 2,
                            Rate = (byte)4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Very professional.",
                            CreatingUserId = 3,
                            Rate = (byte)5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Good, but room to improve.",
                            CreatingUserId = 4,
                            Rate = (byte)3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Excellent skills!",
                            CreatingUserId = 5,
                            Rate = (byte)5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Could be better.",
                            CreatingUserId = 6,
                            Rate = (byte)2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Nice collaboration.",
                            CreatingUserId = 7,
                            Rate = (byte)4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Outstanding developer.",
                            CreatingUserId = 1,
                            Rate = (byte)5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Very reliable.",
                            CreatingUserId = 3,
                            Rate = (byte)4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Good, but slow on some tasks.",
                            CreatingUserId = 4,
                            Rate = (byte)3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Highly recommended.",
                            CreatingUserId = 5,
                            Rate = (byte)5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Needs more attention to detail.",
                            CreatingUserId = 6,
                            Rate = (byte)2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Solid work ethic.",
                            CreatingUserId = 7,
                            Rate = (byte)4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Comment = "Excellent in React.",
                            CreatingUserId = 1,
                            Rate = (byte)5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            Comment = "Great teamwork.",
                            CreatingUserId = 2,
                            Rate = (byte)4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            Comment = "Average communication.",
                            CreatingUserId = 4,
                            Rate = (byte)3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            Comment = "Strong problem-solving skills.",
                            CreatingUserId = 5,
                            Rate = (byte)5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 17,
                            Comment = "Sometimes late with tasks.",
                            CreatingUserId = 6,
                            Rate = (byte)2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            Comment = "Good coding standards.",
                            CreatingUserId = 7,
                            Rate = (byte)4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 19,
                            Comment = "Backend expertise is solid.",
                            CreatingUserId = 1,
                            Rate = (byte)5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            Comment = "Reliable developer.",
                            CreatingUserId = 2,
                            Rate = (byte)4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 21,
                            Comment = "Can improve testing.",
                            CreatingUserId = 3,
                            Rate = (byte)3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 22,
                            Comment = "Knows Spring Boot very well.",
                            CreatingUserId = 5,
                            Rate = (byte)5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 23,
                            Comment = "Slow in code reviews.",
                            CreatingUserId = 6,
                            Rate = (byte)2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 24,
                            Comment = "Good design patterns usage.",
                            CreatingUserId = 7,
                            Rate = (byte)4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 25,
                            Comment = "Excellent frontend skills.",
                            CreatingUserId = 1,
                            Rate = (byte)5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 26,
                            Comment = "Creative UI designs.",
                            CreatingUserId = 2,
                            Rate = (byte)4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 27,
                            Comment = "Occasionally misses deadlines.",
                            CreatingUserId = 3,
                            Rate = (byte)3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 28,
                            Comment = "Very good with Angular.",
                            CreatingUserId = 4,
                            Rate = (byte)5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 29,
                            Comment = "Needs more TypeScript experience.",
                            CreatingUserId = 6,
                            Rate = (byte)2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 30,
                            Comment = "Strong in frontend architecture.",
                            CreatingUserId = 7,
                            Rate = (byte)4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 31,
                            Comment = "Excellent software architect.",
                            CreatingUserId = 1,
                            Rate = (byte)5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 32,
                            Comment = "Great with DDD and CQRS.",
                            CreatingUserId = 2,
                            Rate = (byte)4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 33,
                            Comment = "Sometimes overcomplicates designs.",
                            CreatingUserId = 3,
                            Rate = (byte)3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 34,
                            Comment = "Good microservices design.",
                            CreatingUserId = 4,
                            Rate = (byte)5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 35,
                            Comment = "Needs better documentation.",
                            CreatingUserId = 5,
                            Rate = (byte)2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 36,
                            Comment = "Strong .NET expertise.",
                            CreatingUserId = 7,
                            Rate = (byte)4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 37,
                            Comment = "QA automation expert.",
                            CreatingUserId = 1,
                            Rate = (byte)5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 38,
                            Comment = "Good test coverage.",
                            CreatingUserId = 2,
                            Rate = (byte)4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 39,
                            Comment = "Sometimes misses edge cases.",
                            CreatingUserId = 3,
                            Rate = (byte)3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 40,
                            Comment = "Excellent Selenium skills.",
                            CreatingUserId = 4,
                            Rate = (byte)5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 41,
                            Comment = "Needs improvement in Cypress.",
                            CreatingUserId = 5,
                            Rate = (byte)2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 42,
                            Comment = "Good testing practices.",
                            CreatingUserId = 6,
                            Rate = (byte)4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 43,
                            Comment = "DevOps expertise is top-notch.",
                            CreatingUserId = 1,
                            Rate = (byte)5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 44,
                            Comment = "Very reliable with Kubernetes.",
                            CreatingUserId = 2,
                            Rate = (byte)4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 45,
                            Comment = "Occasionally slow CI/CD pipelines.",
                            CreatingUserId = 3,
                            Rate = (byte)3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 46,
                            Comment = "Excellent Docker knowledge.",
                            CreatingUserId = 4,
                            Rate = (byte)5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 47,
                            Comment = "Needs better Linux troubleshooting.",
                            CreatingUserId = 5,
                            Rate = (byte)2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 48,
                            Comment = "Good DevOps practices.",
                            CreatingUserId = 6,
                            Rate = (byte)4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 49,
                            Comment = "Great data scientist.",
                            CreatingUserId = 1,
                            Rate = (byte)5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 50,
                            Comment = "Good Python skills.",
                            CreatingUserId = 2,
                            Rate = (byte)4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 51,
                            Comment = "Needs more ML optimization.",
                            CreatingUserId = 3,
                            Rate = (byte)3,
                            UserId = 9
                        },
                        new
                        {
                            Id = 52,
                            Comment = "Excellent with TensorFlow.",
                            CreatingUserId = 4,
                            Rate = (byte)5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 53,
                            Comment = "PyTorch skills need improvement.",
                            CreatingUserId = 5,
                            Rate = (byte)2,
                            UserId = 9
                        },
                        new
                        {
                            Id = 54,
                            Comment = "Strong data analysis.",
                            CreatingUserId = 6,
                            Rate = (byte)4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 55,
                            Comment = "Mobile apps are excellent.",
                            CreatingUserId = 1,
                            Rate = (byte)5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 56,
                            Comment = "Great Flutter skills.",
                            CreatingUserId = 2,
                            Rate = (byte)4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 57,
                            Comment = "Sometimes slow in React Native.",
                            CreatingUserId = 3,
                            Rate = (byte)3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 58,
                            Comment = "Good cross-platform knowledge.",
                            CreatingUserId = 4,
                            Rate = (byte)5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 59,
                            Comment = "Firebase integration can improve.",
                            CreatingUserId = 5,
                            Rate = (byte)2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 60,
                            Comment = "Strong mobile architecture.",
                            CreatingUserId = 6,
                            Rate = (byte)4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 61,
                            Comment = "Solid IT solutions.",
                            CreatingUserId = 12,
                            Rate = (byte)4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 62,
                            Comment = "Great APIs.",
                            CreatingUserId = 13,
                            Rate = (byte)5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 63,
                            Comment = "Some delays in projects.",
                            CreatingUserId = 14,
                            Rate = (byte)3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 64,
                            Comment = "Excellent mobile apps.",
                            CreatingUserId = 15,
                            Rate = (byte)5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 65,
                            Comment = "Needs better documentation.",
                            CreatingUserId = 16,
                            Rate = (byte)2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 66,
                            Comment = "Very professional.",
                            CreatingUserId = 17,
                            Rate = (byte)4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 67,
                            Comment = "Excellent recruitment services.",
                            CreatingUserId = 11,
                            Rate = (byte)5,
                            UserId = 12
                        },
                        new
                        {
                            Id = 68,
                            Comment = "Great onboarding processes.",
                            CreatingUserId = 13,
                            Rate = (byte)4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 69,
                            Comment = "Communication can improve.",
                            CreatingUserId = 14,
                            Rate = (byte)3,
                            UserId = 12
                        },
                        new
                        {
                            Id = 70,
                            Comment = "Very professional team.",
                            CreatingUserId = 15,
                            Rate = (byte)5,
                            UserId = 12
                        },
                        new
                        {
                            Id = 71,
                            Comment = "Needs more follow-ups.",
                            CreatingUserId = 16,
                            Rate = (byte)2,
                            UserId = 12
                        },
                        new
                        {
                            Id = 72,
                            Comment = "Reliable HR services.",
                            CreatingUserId = 17,
                            Rate = (byte)4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 73,
                            Comment = "Great SEO campaigns.",
                            CreatingUserId = 11,
                            Rate = (byte)5,
                            UserId = 13
                        },
                        new
                        {
                            Id = 74,
                            Comment = "Effective Google Ads.",
                            CreatingUserId = 12,
                            Rate = (byte)4,
                            UserId = 13
                        },
                        new
                        {
                            Id = 75,
                            Comment = "Reporting can improve.",
                            CreatingUserId = 14,
                            Rate = (byte)3,
                            UserId = 13
                        },
                        new
                        {
                            Id = 76,
                            Comment = "Creative marketing team.",
                            CreatingUserId = 15,
                            Rate = (byte)5,
                            UserId = 13
                        },
                        new
                        {
                            Id = 77,
                            Comment = "Needs faster execution.",
                            CreatingUserId = 16,
                            Rate = (byte)2,
                            UserId = 13
                        },
                        new
                        {
                            Id = 78,
                            Comment = "Strong analytics expertise.",
                            CreatingUserId = 17,
                            Rate = (byte)4,
                            UserId = 13
                        },
                        new
                        {
                            Id = 79,
                            Comment = "Amazing design studio.",
                            CreatingUserId = 11,
                            Rate = (byte)5,
                            UserId = 14
                        },
                        new
                        {
                            Id = 80,
                            Comment = "Good UX/UI work.",
                            CreatingUserId = 12,
                            Rate = (byte)4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 81,
                            Comment = "Could improve accessibility.",
                            CreatingUserId = 13,
                            Rate = (byte)3,
                            UserId = 14
                        },
                        new
                        {
                            Id = 82,
                            Comment = "Very creative designs.",
                            CreatingUserId = 15,
                            Rate = (byte)5,
                            UserId = 14
                        },
                        new
                        {
                            Id = 83,
                            Comment = "Some delays in delivery.",
                            CreatingUserId = 16,
                            Rate = (byte)2,
                            UserId = 14
                        },
                        new
                        {
                            Id = 84,
                            Comment = "Strong prototyping skills.",
                            CreatingUserId = 17,
                            Rate = (byte)4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 85,
                            Comment = "Excellent B2B consulting.",
                            CreatingUserId = 11,
                            Rate = (byte)5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 86,
                            Comment = "Great negotiation skills.",
                            CreatingUserId = 12,
                            Rate = (byte)4,
                            UserId = 15
                        },
                        new
                        {
                            Id = 87,
                            Comment = "Sales approach can improve.",
                            CreatingUserId = 13,
                            Rate = (byte)3,
                            UserId = 15
                        },
                        new
                        {
                            Id = 88,
                            Comment = "Reliable business partner.",
                            CreatingUserId = 14,
                            Rate = (byte)5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 89,
                            Comment = "CRM usage needs improvement.",
                            CreatingUserId = 16,
                            Rate = (byte)2,
                            UserId = 15
                        },
                        new
                        {
                            Id = 90,
                            Comment = "Strong consulting services.",
                            CreatingUserId = 17,
                            Rate = (byte)4,
                            UserId = 15
                        },
                        new
                        {
                            Id = 91,
                            Comment = "Excellent Agile coordination.",
                            CreatingUserId = 11,
                            Rate = (byte)5,
                            UserId = 16
                        },
                        new
                        {
                            Id = 92,
                            Comment = "Good project management.",
                            CreatingUserId = 12,
                            Rate = (byte)4,
                            UserId = 16
                        },
                        new
                        {
                            Id = 93,
                            Comment = "Some sprints delayed.",
                            CreatingUserId = 13,
                            Rate = (byte)3,
                            UserId = 16
                        },
                        new
                        {
                            Id = 94,
                            Comment = "Very organized team.",
                            CreatingUserId = 14,
                            Rate = (byte)5,
                            UserId = 16
                        },
                        new
                        {
                            Id = 95,
                            Comment = "Jira usage can improve.",
                            CreatingUserId = 15,
                            Rate = (byte)2,
                            UserId = 16
                        },
                        new
                        {
                            Id = 96,
                            Comment = "Strong Scrum practices.",
                            CreatingUserId = 17,
                            Rate = (byte)4,
                            UserId = 16
                        },
                        new
                        {
                            Id = 97,
                            Comment = "Excellent IT security.",
                            CreatingUserId = 11,
                            Rate = (byte)5,
                            UserId = 17
                        },
                        new
                        {
                            Id = 98,
                            Comment = "Good networking skills.",
                            CreatingUserId = 12,
                            Rate = (byte)4,
                            UserId = 17
                        },
                        new
                        {
                            Id = 99,
                            Comment = "Monitoring can improve.",
                            CreatingUserId = 13,
                            Rate = (byte)3,
                            UserId = 17
                        },
                        new
                        {
                            Id = 100,
                            Comment = "Reliable server management.",
                            CreatingUserId = 14,
                            Rate = (byte)5,
                            UserId = 17
                        },
                        new
                        {
                            Id = 101,
                            Comment = "Needs faster incident response.",
                            CreatingUserId = 15,
                            Rate = (byte)2,
                            UserId = 17
                        },
                        new
                        {
                            Id = 102,
                            Comment = "Strong DevSecOps practices.",
                            CreatingUserId = 16,
                            Rate = (byte)4,
                            UserId = 17
                        },
                        new
                        {
                            Id = 103,
                            Comment = "Great business analytics.",
                            CreatingUserId = 11,
                            Rate = (byte)5,
                            UserId = 18
                        },
                        new
                        {
                            Id = 104,
                            Comment = "Good SQL skills.",
                            CreatingUserId = 12,
                            Rate = (byte)4,
                            UserId = 18
                        },
                        new
                        {
                            Id = 105,
                            Comment = "ETL pipelines need improvement.",
                            CreatingUserId = 13,
                            Rate = (byte)3,
                            UserId = 18
                        },
                        new
                        {
                            Id = 106,
                            Comment = "Excellent BI knowledge.",
                            CreatingUserId = 14,
                            Rate = (byte)5,
                            UserId = 18
                        },
                        new
                        {
                            Id = 107,
                            Comment = "UML diagrams can be clearer.",
                            CreatingUserId = 15,
                            Rate = (byte)2,
                            UserId = 18
                        },
                        new
                        {
                            Id = 108,
                            Comment = "Strong data warehousing skills.",
                            CreatingUserId = 16,
                            Rate = (byte)4,
                            UserId = 18
                        },
                        new
                        {
                            Id = 109,
                            Comment = "Excellent IT support.",
                            CreatingUserId = 11,
                            Rate = (byte)5,
                            UserId = 19
                        },
                        new
                        {
                            Id = 110,
                            Comment = "Reliable helpdesk services.",
                            CreatingUserId = 12,
                            Rate = (byte)4,
                            UserId = 19
                        },
                        new
                        {
                            Id = 111,
                            Comment = "Troubleshooting can be faster.",
                            CreatingUserId = 13,
                            Rate = (byte)3,
                            UserId = 19
                        });
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employer"
                        });
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Krs")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("KRS");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nip")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("NIP");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Warsaw, Aleje Jerozolimskie 5",
                            CompanyName = "GoodCompany",
                            Country = "Poland",
                            Description = "Doświadczony programista .NET i Java z pasją do nowych technologii.",
                            Email = "john.smith@gmail.com",
                            FirstName = "John",
                            Krs = "0123456789",
                            LastName = "Smith",
                            Nip = "0123456789",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ7CNapDlFHbpARLMz9ZeGMG/s+/RtrNzI7uz1Bh+E0hMXfYW0/rBdK2D+uo1VvK5g==",
                            RoleId = 1,
                            Tags = "[\".NET\",\"Java\",\"C#\",\"SQL\",\"Azure\",\"Microservices\"]"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Krakow, Main Street 12",
                            CompanyName = "DevMasters",
                            Country = "Poland",
                            Description = "Senior developer z wieloletnim doświadczeniem w pracy z chmurą Azure.",
                            Email = "michael.brown@gmail.com",
                            FirstName = "Michael",
                            Krs = "9876543210",
                            LastName = "Brown",
                            Nip = "1234567890",
                            PasswordHash = "AQAAAAIAAYagAAAAEMsfhy8G5+yIIc0WR1w4gaxU0RhmHbb1IRb8wHfDugCl5p0Icp8ecv9To2JHzbRG2Q==",
                            RoleId = 1,
                            Tags = "[\"C#\",\"Azure\",\"DevOps\",\"Cloud\",\"ASP.NET Core\",\"SQL\"]"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Gdansk, Dluga 1",
                            CompanyName = "WebSolutions",
                            Country = "Poland",
                            Description = "Fullstack developer z doświadczeniem w React i Node.js.",
                            Email = "anna.kowalska@gmail.com",
                            FirstName = "Anna",
                            Krs = "6655443322",
                            LastName = "Kowalska",
                            Nip = "2233445566",
                            PasswordHash = "AQAAAAIAAYagAAAAECOmenVW2+X+tCAbL/5rzUkHctr3TDcXucX/qipHBffLwXKwBU3VZb/5rn3ZTTGnBA==",
                            RoleId = 1,
                            Tags = "[\"React\",\"Node.js\",\"JavaScript\",\"TypeScript\",\"GraphQL\",\"MongoDB\"]"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Lodz, Piotrkowska 100",
                            CompanyName = "CloudTech",
                            Country = "Poland",
                            Description = "Specjalista backend z dużą wiedzą w zakresie Java i Spring Boot.",
                            Email = "piotr.nowak@gmail.com",
                            FirstName = "Piotr",
                            Krs = "5566778899",
                            LastName = "Nowak",
                            Nip = "9988776655",
                            PasswordHash = "AQAAAAIAAYagAAAAEMc62fJoEDiN6+Oe98EQrXw3ed43XBhH32b0yOWiEqBPTZ81wTspRagM3Kncalmtaw==",
                            RoleId = 1,
                            Tags = "[\"Java\",\"Spring Boot\",\"Hibernate\",\"Kotlin\",\"Microservices\",\"Docker\"]"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Poznan, Swiety Marcin 45",
                            CompanyName = "UIWorks",
                            Country = "Poland",
                            Description = "Ekspert frontend z doświadczeniem w Angular i TypeScript.",
                            Email = "karolina.mazur@gmail.com",
                            FirstName = "Karolina",
                            Krs = "4333222111",
                            LastName = "Mazur",
                            Nip = "1112223334",
                            PasswordHash = "AQAAAAIAAYagAAAAEB1zlw2u2YqkF4oD450Y+Za2Ez7hl4R7VSXTQE1aNANfrNLnK7zmmaVg55r3yRG0ug==",
                            RoleId = 1,
                            Tags = "[\"Angular\",\"TypeScript\",\"RxJS\",\"SCSS\",\"Material UI\",\"HTML5\"]"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Szczecin, Aleja Piastów 10",
                            CompanyName = "SoftBuild",
                            Country = "Poland",
                            Description = "Architekt oprogramowania specjalizujący się w .NET i mikroserwisach.",
                            Email = "pawel.zielinski@gmail.com",
                            FirstName = "Pawel",
                            Krs = "0999888777",
                            LastName = "Zielinski",
                            Nip = "7778889990",
                            PasswordHash = "AQAAAAIAAYagAAAAEGrwY0RMYs2h0mhSGn9oJ6yeJMsjPCb4XUrQpXrt6dVebfzhRTdn7tbuAq7/aOxvFg==",
                            RoleId = 1,
                            Tags = "[\".NET\",\"Microservices\",\"DDD\",\"CQRS\",\"Azure\",\"Kubernetes\"]"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Warsaw, Nowy Swiat 20",
                            CompanyName = "TestIt",
                            Country = "Poland",
                            Description = "Inżynier QA z doświadczeniem w automatyzacji testów.",
                            Email = "magdalena.wisniewska@gmail.com",
                            FirstName = "Magdalena",
                            Krs = "5544332211",
                            LastName = "Wisniewska",
                            Nip = "1122334455",
                            PasswordHash = "AQAAAAIAAYagAAAAELl2Vn/E+Nn0QEAvcZldYHE4SHTuJ8K9OLi6dPaZyxXr9oE4ljgi01Z1DQWRkfgFYw==",
                            RoleId = 1,
                            Tags = "[\"Selenium\",\"Cypress\",\"JUnit\",\"TestNG\",\"Postman\",\"Playwright\"]"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Katowice, Mickiewicza 8",
                            CompanyName = "OpsMasters",
                            Country = "Poland",
                            Description = "Inżynier DevOps specjalizujący się w Docker i Kubernetes.",
                            Email = "adam.lewandowski@gmail.com",
                            FirstName = "Adam",
                            Krs = "9988776655",
                            LastName = "Lewandowski",
                            Nip = "5566778899",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ4eua7Gd6vT0F+I36T3i8umoQwu3FzGCwQy/42+8SZWuFDH4LiejVlloRUa1G1xcg==",
                            RoleId = 1,
                            Tags = "[\"Docker\",\"Kubernetes\",\"Helm\",\"Terraform\",\"CI/CD\",\"Linux\"]"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Bydgoszcz, Główna 22",
                            CompanyName = "DataVision",
                            Country = "Poland",
                            Description = "Data scientist z doświadczeniem w Python i machine learning.",
                            Email = "dorota.kaczmarek@gmail.com",
                            FirstName = "Dorota",
                            Krs = "5544211332",
                            LastName = "Kaczmarek",
                            Nip = "3322114455",
                            PasswordHash = "AQAAAAIAAYagAAAAENN4/TyTxyy5GEK8u5zO4wBiAzunqigH97nIyreHzHTB9RtLdRNCaRA3r1Vk4lIsvw==",
                            RoleId = 1,
                            Tags = "[\"Python\",\"ML\",\"Pandas\",\"TensorFlow\",\"PyTorch\",\"Data Mining\"]"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Opole, Krakowska 15",
                            CompanyName = "Appify",
                            Country = "Poland",
                            Description = "Programista aplikacji mobilnych w Flutter i React Native.",
                            Email = "marcin.wozniak@gmail.com",
                            FirstName = "Marcin",
                            Krs = "2211009988",
                            LastName = "Wozniak",
                            Nip = "8899001122",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ5JhhZuOLGDl+fUS549iK1rG0I+/PGrIL82Yuedq3ZJifvdVpHrrp6b+9dFGc1Khw==",
                            RoleId = 1,
                            Tags = "[\"Flutter\",\"React Native\",\"Dart\",\"iOS\",\"Android\",\"Firebase\"]"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Bialystok, Aleje Jerozolimskie 5",
                            CompanyName = "PerfectCompany",
                            Country = "Poland",
                            Description = "Firma IT specjalizująca się w rozwiązaniach webowych i mobilnych dla sektora e-commerce.",
                            Email = "jack.smith@gmail.com",
                            FirstName = "Jack",
                            Krs = "0123456789",
                            LastName = "Smith",
                            Nip = "0123456789",
                            PasswordHash = "AQAAAAIAAYagAAAAEMVoKZsXjHEYR3bJIifhYirRz/XIidOVzBA4xB4b067NG5NUYQsegib2OY/qUAIvPA==",
                            RoleId = 2,
                            Tags = "[\".NET\",\"Java\",\"E-Commerce\",\"Mobile Apps\",\"Cloud\",\"API\"]"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Warsaw, Prosta 4",
                            CompanyName = "HRPlus",
                            Country = "Poland",
                            Description = "Agencja HR oferująca kompleksowe usługi rekrutacyjne i doradztwo personalne.",
                            Email = "lisa.jones@gmail.com",
                            FirstName = "Lisa",
                            Krs = "3213213210",
                            LastName = "Jones",
                            Nip = "1231231230",
                            PasswordHash = "AQAAAAIAAYagAAAAENxrDdrhfsjhd6PSI0nfnlbcdm9QCkJFOvJtTEeqjNGZdyw8IRlfZyad6tO1GjIZiw==",
                            RoleId = 2,
                            Tags = "[\"Recruitment\",\"Onboarding\",\"HR\",\"Employer Branding\",\"Talent Sourcing\"]"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Lublin, Krakowskie Przedmieście 33",
                            CompanyName = "MarketLead",
                            Country = "Poland",
                            Description = "Agencja marketingowa zajmująca się kampaniami SEO i reklamami Google Ads.",
                            Email = "tomasz.malinowski@gmail.com",
                            FirstName = "Tomasz",
                            Krs = "7666555444",
                            LastName = "Malinowski",
                            Nip = "4445556667",
                            PasswordHash = "AQAAAAIAAYagAAAAEOBa89T0i1U8OTvCS3vNLg7GTlDTwKonoJTsCkQQrq/rQbutwW3DELXNSW/nCg9U6A==",
                            RoleId = 2,
                            Tags = "[\"SEO\",\"Google Ads\",\"SEM\",\"Content Marketing\",\"Analytics\",\"Copywriting\"]"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Warsaw, Marszalkowska 7",
                            CompanyName = "DesignHub",
                            Country = "Poland",
                            Description = "Studio projektowe tworzące nowoczesne interfejsy i doświadczenia użytkowników.",
                            Email = "ewa.adamska@gmail.com",
                            FirstName = "Ewa",
                            Krs = "4131211101",
                            LastName = "Adamska",
                            Nip = "1011121314",
                            PasswordHash = "AQAAAAIAAYagAAAAEJTSicZIdPbEfgZMC4DNc/zicze+ljM8eiYS+1/zmRVU8e4FePlgvhNM8fPf6nmVlg==",
                            RoleId = 2,
                            Tags = "[\"Figma\",\"UX\",\"UI Design\",\"Prototyping\",\"Adobe XD\",\"Accessibility\"]"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Kielce, Sienkiewicza 11",
                            CompanyName = "BizGrow",
                            Country = "Poland",
                            Description = "Firma doradcza specjalizująca się w obsłudze klientów B2B i negocjacjach handlowych.",
                            Email = "grzegorz.kubiak@gmail.com",
                            FirstName = "Grzegorz",
                            Krs = "0099887766",
                            LastName = "Kubiak",
                            Nip = "6677889900",
                            PasswordHash = "AQAAAAIAAYagAAAAEPiFHu+5RQtuqmoHwCPae8cxiyS06cftCO3IhJ4QjS/8w/A+jE+pWTS/lNu4PF2npQ==",
                            RoleId = 2,
                            Tags = "[\"B2B\",\"Negotiations\",\"Sales\",\"Consulting\",\"Partnerships\",\"CRM\"]"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Rzeszow, Grunwaldzka 6",
                            CompanyName = "PMExperts",
                            Country = "Poland",
                            Description = "Firma zajmująca się koordynacją projektów IT w metodykach Agile i Scrum.",
                            Email = "joanna.olszewska@gmail.com",
                            FirstName = "Joanna",
                            Krs = "1100998877",
                            LastName = "Olszewska",
                            Nip = "7788990011",
                            PasswordHash = "AQAAAAIAAYagAAAAEHBqUe4JFAvRDtrbobpd+G9fjGdu+BVuV9Di4QhRDsGE7YRoaq2KdSXO0iFnH3zGsA==",
                            RoleId = 2,
                            Tags = "[\"Agile\",\"Scrum\",\"Kanban\",\"Project Management\",\"Jira\",\"Confluence\"]"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Gdynia, Skwer Kosciuszki 9",
                            CompanyName = "ITSecure",
                            Country = "Poland",
                            Description = "Dostawca usług IT w zakresie administracji serwerami i bezpieczeństwa sieci.",
                            Email = "krzysztof.urban@gmail.com",
                            FirstName = "Krzysztof",
                            Krs = "2233446655",
                            LastName = "Urban",
                            Nip = "5566443322",
                            PasswordHash = "AQAAAAIAAYagAAAAEDTPnftqwuB6K8DfdW2jD+uGU5yMK8FVQLW+GcKVwwB+vWd5ph/kRcq/Sj5c3eGV5Q==",
                            RoleId = 2,
                            Tags = "[\"Linux\",\"Networking\",\"Security\",\"Firewalls\",\"Monitoring\",\"DevSecOps\"]"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Bielsko-Biala, Partyzantów 18",
                            CompanyName = "BizAnalytics",
                            Country = "Poland",
                            Description = "Firma analityczna świadcząca usługi w zakresie analizy biznesowej i baz danych.",
                            Email = "monika.dabrowska@gmail.com",
                            FirstName = "Monika",
                            Krs = "7766554433",
                            LastName = "Dabrowska",
                            Nip = "3344556677",
                            PasswordHash = "AQAAAAIAAYagAAAAEAuz58HpvZLgkq5trIcFzqxHnVzxRr7sKCsgFnmVysgBcYXa7CqpLy3+x/IcQMMzrg==",
                            RoleId = 2,
                            Tags = "[\"SQL\",\"UML\",\"Business Analysis\",\"BI\",\"ETL\",\"Data Warehousing\"]"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Torun, Szeroka 2",
                            CompanyName = "HelpDeskPro",
                            Country = "Poland",
                            Description = "Firma świadcząca wsparcie techniczne oraz konsultacje w obszarze IT.",
                            Email = "dawid.pietrzak@gmail.com",
                            FirstName = "Dawid",
                            Krs = "6655443322",
                            LastName = "Pietrzak",
                            Nip = "2233445566",
                            PasswordHash = "AQAAAAIAAYagAAAAEHV3CKgn0HZmWKSngsylc1MFV/5Pmc8GB3SObAobvS6yqX5DPyB9j18e0gew7/BOkA==",
                            RoleId = 2,
                            Tags = "[\"Customer Service\",\"ITIL\",\"Helpdesk\",\"Support\",\"Troubleshooting\",\"Windows\"]"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Plock, Tumskie 14",
                            CompanyName = "ContentLab",
                            Country = "Poland",
                            Description = "Agencja kreatywna specjalizująca się w tworzeniu treści marketingowych.",
                            Email = "natalia.sawicka@gmail.com",
                            FirstName = "Natalia",
                            Krs = "5566778899",
                            LastName = "Sawicka",
                            Nip = "9988776655",
                            PasswordHash = "AQAAAAIAAYagAAAAEANCw92K961LhMDyVK3PyLH4HFgx6exgnNHl3CzG0BErQ12WVsy/3czUuIr+hg4qVQ==",
                            RoleId = 2,
                            Tags = "[\"Copywriting\",\"Social Media\",\"Marketing\",\"Storytelling\",\"Branding\",\"Creative\"]"
                        });
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.UserPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPhoto", (string)null);
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.Job", b =>
                {
                    b.HasOne("Freelancer.Backend.Domain.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Job__UserId__02084FDA");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.JobPhoto", b =>
                {
                    b.HasOne("Freelancer.Backend.Domain.Job", "Job")
                        .WithMany("JobPhotos")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__JobPhoto__JobId__07C12930");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.JobRequest", b =>
                {
                    b.HasOne("Freelancer.Backend.Domain.Job", "Job")
                        .WithMany("JobRequests")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserJobs__JobId__03F0984C");

                    b.HasOne("Freelancer.Backend.Domain.User", "User")
                        .WithMany("JobsUser")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserJobs__UserId__02FC7413");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.JobsUser", b =>
                {
                    b.HasOne("Freelancer.Backend.Domain.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK__JobsUsers__JobId__05D8E0BE");

                    b.HasOne("Freelancer.Backend.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__JobsUsers__UserI__04E4BC85");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.Rating", b =>
                {
                    b.HasOne("Freelancer.Backend.Domain.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Rating__UserId__06CD04F7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.User", b =>
                {
                    b.HasOne("Freelancer.Backend.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__User__RoleId__7E37BEF6");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.UserPhoto", b =>
                {
                    b.HasOne("Freelancer.Backend.Domain.User", "User")
                        .WithOne("Photo")
                        .HasForeignKey("Freelancer.Backend.Domain.UserPhoto", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__User__PhotoId__7F2BE32F");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.Job", b =>
                {
                    b.Navigation("JobPhotos");

                    b.Navigation("JobRequests");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Freelancer.Backend.Domain.User", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("JobsUser");

                    b.Navigation("Photo");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
